version: "3"

services:
  proshop:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
      NODE_ENV: ${NODE_ENV}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PORT: ${PORT}
    container_name: proshop
networks:
  default:
    external:
      name: nmamager_default
